language: objective-c

xcode_project: Dose.xcodeproj
xcode_scheme: [ 'Dose iOS', 'Dose OSX' ]
osx_image: xcode7.2
xcode_sdk: [macosx10.11, iphonesimulator9.1 ]

matrix:
    exclude:
    - xcode_sdk: macosx10.11
      xcode_scheme: 'Dose iOS'
    - xcode_sdk: iphonesimulator9.1
      xcode_scheme: 'Dose OSX'

